"""update student table

Revision ID: 2561a42d440d
Revises: c4a0b2505525
Create Date: 2024-04-07 14:08:23.750983

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2561a42d440d'
down_revision = 'c4a0b2505525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Father_occupation', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('Mother_occupation', sa.String(length=100), nullable=False))
        batch_op.alter_column('academic_year',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('admission_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('father_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('mother_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=mysql.VARCHAR(length=15),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('mobile',
               existing_type=mysql.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('mother_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('father_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('admission_date',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('academic_year',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_column('Mother_occupation')
        batch_op.drop_column('Father_occupation')

    # ### end Alembic commands ###
