"""update Subject table

Revision ID: 31237f507e19
Revises: 114cc742a6c8
Create Date: 2024-03-27 22:19:50.213938

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31237f507e19'
down_revision = '114cc742a6c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student__subject__results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marks', sa.Float(), nullable=False))
        batch_op.drop_column('grade')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subject_name', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('subject_ibfk_1', type_='foreignkey')
        batch_op.drop_column('name')
        batch_op.drop_column('class_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key('subject_ibfk_1', 'class', ['class_id'], ['id'])
        batch_op.drop_column('subject_name')

    with op.batch_alter_table('student__subject__results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('grade', mysql.FLOAT(), nullable=False))
        batch_op.drop_column('marks')

    # ### end Alembic commands ###
