"""update student table

Revision ID: 4eb20a60f586
Revises: 6f7657012aad
Create Date: 2024-04-07 15:14:50.609005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4eb20a60f586'
down_revision = '6f7657012aad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_occupation', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mother_occupation', sa.String(length=100), nullable=False))
        batch_op.drop_column('Father_occupation')
        batch_op.drop_column('Mother_occupation')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Mother_occupation', mysql.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('Father_occupation', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('mother_occupation')
        batch_op.drop_column('father_occupation')

    # ### end Alembic commands ###
