"""update Student table

Revision ID: 9994f807420e
Revises: 947bff0b0ab5
Create Date: 2024-03-27 16:23:09.835432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9994f807420e'
down_revision = '947bff0b0ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admission_date', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('father_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mother_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('mobile', sa.String(length=15), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('mobile')
        batch_op.drop_column('address')
        batch_op.drop_column('mother_name')
        batch_op.drop_column('father_name')
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('admission_date')

    # ### end Alembic commands ###
