"""update student table

Revision ID: c3c59c51eb55
Revises: 4eb20a60f586
Create Date: 2024-04-07 16:23:40.810863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c59c51eb55'
down_revision = '4eb20a60f586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_occupation', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('mother_occupation', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('mother_occupation')
        batch_op.drop_column('father_occupation')

    # ### end Alembic commands ###
