"""update student table

Revision ID: c4a0b2505525
Revises: 4a2155dc1d9e
Create Date: 2024-04-04 13:59:18.458666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4a0b2505525'
down_revision = '4a2155dc1d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.alter_column('academic_year',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
